云原生网络部分更新
CloudNativeIndustryAlliance/whitepaper2020 pull request #10
Opened 2020-06-10 11:42 UTC by torresvskaka

2020-06-10 13:29 UTC, Alyyyyyy approved these changes

2020-06-11 02:19 UTC, yu8833 requested changes

2020-06-11 02:19 UTC, yu8833 commented on ch3/新技术-云原生网络.md
> +优势|*网络性能高<br>*支持Kubernetes原生负载均衡和网络策略机制<br>*符合传统网络的监管要求|*物理网络无侵入<br>*支持Kubernetes原生负载均衡和网络策略机制|*网络性能高<br>*可直接月IaaS层网络通信，易于迁移<br>*符合传统的监管需求
可直接月IaaS层网络通信，易于迁移

“月“字是笔误吧？

2020-06-11 02:19 UTC, yu8833 commented on ch3/新技术-云原生网络.md
> +缺点|*大规模应用场景需要交换机与BGP打通|*存在封装影响性能<br>*排查问题难，需引入额外排查工具<br>*无法与传统的网络监管模式兼容|*网络管理依赖于物理网络<br>*大部分方案无法复用Kubernetes的网络优势求
“求“字是笔误吧？

2020-06-11 02:19 UTC, yu8833 commented on ch3/新技术-云原生网络.md
> +可选方案|*Calico BGP<br>*Flannel Host Gateway<br>*Kube-router<br>*Contiv BGP|*Calico IPIP,VXLAN<br>*Flannel VXLAN, UDP<br>*WEAVE<br>*Canal<br>*SDN方案|*Lunix Bridge<br>*Macvlan<br>*SRIOV<br>*OVS Bridge<br>
是不是有更多的方案？
例如multus

2020-06-11 02:19 UTC, YuPengZTE commented on ch3/新技术-云原生网络.md
> +随着云原生的普及，服务端点（容器）的规模快速增长（十万甚至百万），互访场景越来越丰富，比如：跨集群、跨VPC、混合云互访等，这要求容器端点具有与宿主节点（虚机）相同的互通能力，VPC-Native的容器网络已经成为趋势，容器成为VPC中的一等公民，容器（POD）和服务（ClusterIP）具有独立VPC的子网地址，甚至具有独立的直通网口（如：ENI）,这样在获得更高转发性能、更低损耗的同时，具有
VPC-Native的容器网络已经成为趋势
这一点是否需要提供论据再论证一下？
或者先不提？

2020-06-11 02:19 UTC, YuPengZTE commented on ch3/新技术-云原生网络.md
> +平台的安全问题在所有的平台演进和建设过程中一直扮演着非常重要，但是不十分紧急的角色。因此，在容器安全建设上，大部分组织都是采取防守和被动姿态。但是本身在近几年陆续爆出大量的基于容器平台的安全隐患以及在工信部和网信办联合组织的“护网行动”的大背景之下，容器安全已经成为云原生底座无法绕开的一个问题。 容器网络安全则在整个底座安全里面扮演了非常重要的角色，因此也将成为之后的CNI网络演进的方向和趋势。
和上面小节的内容重复

2020-06-18 02:59 UTC, rootsongjc commented
那个全景图能否使用图注的方式来标明不同颜色的框的含义？现在看上去很多重复的“中国开源”，闭源的软件使用暗色调有没有说明是什么含义，表意不明。

2020-06-18 08:18 UTC, torresvskaka commented
> 那个全景图能否使用图注的方式来标明不同颜色的框的含义？现在看上去很多重复的“中国开源”，闭源的软件使用暗色调有没有说明是什么含义，表意不明。

好的，在下个版本中我把图示添加上。还有一些反馈的logo未添加，下个版本中一起修正。

2020-06-18 08:44 UTC, torresvskaka commented on ch3/新技术-云原生网络.md
> +优势|*网络性能高<br>*支持Kubernetes原生负载均衡和网络策略机制<br>*符合传统网络的监管要求|*物理网络无侵入<br>*支持Kubernetes原生负载均衡和网络策略机制|*网络性能高<br>*可直接月IaaS层网络通信，易于迁移<br>*符合传统的监管需求
笔误。。用于，已修改

2020-06-18 08:45 UTC, torresvskaka commented on ch3/新技术-云原生网络.md
> +缺点|*大规模应用场景需要交换机与BGP打通|*存在封装影响性能<br>*排查问题难，需引入额外排查工具<br>*无法与传统的网络监管模式兼容|*网络管理依赖于物理网络<br>*大部分方案无法复用Kubernetes的网络优势求
已修正

2020-06-18 08:46 UTC, torresvskaka commented on ch3/新技术-云原生网络.md
> +可选方案|*Calico BGP<br>*Flannel Host Gateway<br>*Kube-router<br>*Contiv BGP|*Calico IPIP,VXLAN<br>*Flannel VXLAN, UDP<br>*WEAVE<br>*Canal<br>*SDN方案|*Lunix Bridge<br>*Macvlan<br>*SRIOV<br>*OVS Bridge<br>
该部分内容是从之前专家提供的材料中总结的~如果有补充可以私信给我，我在完善哈

2020-06-18 08:50 UTC, torresvskaka commented on ch3/新技术-云原生网络.md
> +随着云原生的普及，服务端点（容器）的规模快速增长（十万甚至百万），互访场景越来越丰富，比如：跨集群、跨VPC、混合云互访等，这要求容器端点具有与宿主节点（虚机）相同的互通能力，VPC-Native的容器网络已经成为趋势，容器成为VPC中的一等公民，容器（POD）和服务（ClusterIP）具有独立VPC的子网地址，甚至具有独立的直通网口（如：ENI）,这样在获得更高转发性能、更低损耗的同时，具有
暂时删掉这个论点了

2020-06-18 08:50 UTC, torresvskaka commented on ch3/新技术-云原生网络.md
> +平台的安全问题在所有的平台演进和建设过程中一直扮演着非常重要，但是不十分紧急的角色。因此，在容器安全建设上，大部分组织都是采取防守和被动姿态。但是本身在近几年陆续爆出大量的基于容器平台的安全隐患以及在工信部和网信办联合组织的“护网行动”的大背景之下，容器安全已经成为云原生底座无法绕开的一个问题。 容器网络安全则在整个底座安全里面扮演了非常重要的角色，因此也将成为之后的CNI网络演进的方向和趋势。
已修正~

2020-06-18 08:58 UTC, merged